### ISSUE TITLE
2. Configure apt sources

### ISSUE THREAD

**Issue by cpcn** [LearningRegistry/LearningRegistry#293]
Is there anything for debian distributions?

**Comment by joehobson** [comment]
I'm assuming you're asking about the install guides in the docs - correct? Although the software should work on most _unix-like_ OSes, with limited dev and documentation time, we have traditionally only provided docs on Ubuntu. A few years ago I would have said that you shouldn't have any trouble getting it running on Debian, but considering the age of CouchDB, that may not be true anymore.

If you do run through setup with Debian and you'd like to write an install guide (a copy of the ubuntu guide with updates would suffice), please submit a pull request so that others can benefit. Thanks!
